### PR TITLE
Fix code scanning alert no. 80: Server-side request forgery

### PR DESCRIPTION
**Pull request by heyvard**
Fixes [https://github.com/navikt/ditt-sykefravaer/security/code-scanning/80](https://github.com/navikt/ditt-sykefravaer/security/code-scanning/80)

To fix the SSRF vulnerability, we need to validate the `sykmeldingId` parameter before using it to construct the URL. We can implement an allow-list of valid `sykmeldingId` values or use a regular expression to ensure that the `sykmeldingId` conforms to an expected format. This will prevent attackers from injecting malicious URLs.

1. Implement a validation function to check the `sykmeldingId` against an allow-list or a regular expression.
2. Use this validation function in `useGetSykmeldingIdParam` to ensure the `sykmeldingId` is valid before returning it.
3. Update the `fetchMedRequestId` function to handle invalid `sykmeldingId` values appropriately.

_Suggested fixes powered by Copilot Autofix. Review carefully before merging._

### CODE REVIEW

**Review by eirik1502 — COMMENTED** [review]
Er ikke den valideringa her litt vel generisk? Den aksepterer ganske mye

**Comment by heyvard** [comment]
> Er ikke den valideringa her litt vel generisk? Den aksepterer ganske mye

Den aksepterer vel bare uuid?

**Comment by eirik1502** [comment]
Aksepterer alle sekvenser med disse tegnene [a-zA-Z0-9-]

**Comment by eirik1502** [comment]
True, men ser ut som vi har impoerter uuid bibliteket, og kan bruke [uuid.validate()](https://www.npmjs.com/package/uuid#uuidvalidatestr)

**Review by eirik1502 — APPROVED** [review]
Sweetzo, vurder [uuid.validate()](https://www.npmjs.com/package/uuid#uuidvalidatestr)

**Comment by eirik1502** [comment]
I C, kjør på

**Pull request merged**
